### ISSUE TITLE
Updating Profile Picture - 500

### ISSUE THREAD

**Issue by greggthebax** [ues-io/uesio#3816]
When I edit my profile and add a profile picture 37kb I get a 500.

**Comment by humandad** [comment]
I can't repro this. Can you reproduce this consistently?

**Comment by abelcloudmasters** [comment]
Works for me as well

![Screenshot 2024-02-07 at 10 39 11](https://github.com/ues-io/uesio/assets/65349612/4ee77731-1067-4684-9c33-4f1940cad64f)

**Comment by abelcloudmasters** [comment]
It also works in prod for your username @greggthebax maybe your session expired when you were trying to upload the picture. Feel free to close this issue if you think is solved.

![Screenshot 2024-02-07 at 10 43 13](https://github.com/ues-io/uesio/assets/65349612/0900defe-8066-4664-97f2-93574bd80ed4)

**Comment by greggthebax** [comment]
Works now thanks. Sure I tried a dozen times :)
