### ISSUE TITLE
Cannot update Reference fields once created

### ISSUE THREAD

**Issue by zachelrath** [ues-io/uesio#4318]
**Steps to reproduce:**

1. From Studio, create / edit a Reference field.
2. Try to change a property value, e.g. change "Required" from true to false, but ONLY change that property.
3. Save.

**Expected result:**
1. Change would save successfully.

**Actual result:**
1. Change fails with error: "Field Path not found: uesio/studio.reference->uesio/studio.multicollection"

**Workaround**

Make sure to also change the "Ref. Collection" field's value at the same time, and then it will successfully save. 

** Root cause **

Error is coming from systembot_before_field handler, which is expecting that the "uesio/studio.reference" STRUCT will always be present in a field update, even if you're just changing the "required" field's value:
```
			case "REFERENCE":
			isMultiCollection, _ := change.GetField("uesio/studio.reference->uesio/studio.multicollection")
			if err != nil {
				return err
			}
			if isMultiCollection == nil || isMultiCollection.(bool) == false {
				err = depMap.AddRequired(change, "collection", "uesio/studio.reference->uesio/studio.collection")
				if err != nil {
					return err
				}
			}
```

<img width="1351" alt="Screenshot 2024-11-29 at 7 43 02 AM" src="https://github.com/user-attachments/assets/899b8677-500d-49bf-8d05-514860f1a134">

**Comment by humandad** [comment]
I added a failing test for this. I'll fix it when I get a chance.

https://github.com/ues-io/uesio/pull/4320

**Comment by humandad** [comment]
This should be fixed here. https://github.com/ues-io/uesio/pull/4320
