### ISSUE TITLE
Add User Access Tokens to Studio UI

### ISSUE THREAD

**Issue by zachelrath** [ues-io/uesio#4319]
In order to implement user-based security row-level security models, it is necessary to be able to define User Access Tokens. Currently these are not accessible from the Studio UI unless you manually enter /useraccesstokens into the URL - there should be some way to find this route, either via a main nav item, or some other way.

**Comment by humandad** [comment]
I think this is behind a feature flag. If you give yourself the feature, it should be there.

<img width="1135" alt="Screenshot 2024-11-30 at 11 22 53 AM" src="https://github.com/user-attachments/assets/5ce19f22-9506-4f10-9e22-bd2ecbfddafc">

**Comment by humandad** [comment]
I'd be happy to remove the feature flag completely though, I think the original thinking behind the feature flag was that user access tokens were complicated and poorly documented. But there are other similar metadata types that fit that same category that are not hiding behind a feature flat.
