### ISSUE TITLE
chore: replace deprecated tslint

### ISSUE THREAD

**Issue by techfg** [ues-io/uesio#4356]
tslint and associated tooling (e.g., vscode extension) has been [deprecated](https://github.com/Microsoft/vscode-typescript-tslint-plugin).

Upgrade to [eslint](https://github.com/typescript-eslint/typescript-eslint#typescript-eslint) or consider [biome](https://biomejs.dev/).

**Comment by humandad** [comment]
I don't think we actually use tslint anywhere in uesio. There was just a few references to it in `nx.json` and `.vscode/extensions.json`. I'll make a PR to remove those.

**Comment by humandad** [comment]
Fixed in https://github.com/ues-io/uesio/pull/4360

**Comment by techfg** [comment]
Yeah, realized after creating issue that eslint was used, just some dangling tslint references remained.  Thanks for addressing!
